-- بيانات أولية: 10 تصنيفات + 150 سؤال/جواب + تدفق التأهيل + قواعد الترشيح
-- هذه أجوبة مسودّة أولية بأسلوب عام واقعي، الهدف من لوحة الإدارة (CRUD) مراجعتها لاحقًا بأجوبة رسمية دقيقة.

-- =========================================================
-- 1) التصنيفات
-- =========================================================

insert into categories (id, name_ar, name_en, sort_order) values (gen_random_uuid(), 'عن رمال X', 'About Rimal X', 1);
insert into categories (id, name_ar, name_en, sort_order) values (gen_random_uuid(), 'حاضنة الأعمال', 'Business Incubator', 2);
insert into categories (id, name_ar, name_en, sort_order) values (gen_random_uuid(), 'مسرعة الأعمال', 'Business Accelerator', 3);
insert into categories (id, name_ar, name_en, sort_order) values (gen_random_uuid(), 'مساحات العمل', 'Workspaces', 4);
insert into categories (id, name_ar, name_en, sort_order) values (gen_random_uuid(), 'الدورات التدريبية', 'Training Courses', 5);
insert into categories (id, name_ar, name_en, sort_order) values (gen_random_uuid(), 'الفعاليات', 'Events', 6);
insert into categories (id, name_ar, name_en, sort_order) values (gen_random_uuid(), 'القطاعات المستهدفة', 'Target Sectors', 7);
insert into categories (id, name_ar, name_en, sort_order) values (gen_random_uuid(), 'الدعم والاستشارات', 'Support & Consulting', 8);
insert into categories (id, name_ar, name_en, sort_order) values (gen_random_uuid(), 'الشراكات', 'Partnerships', 9);
insert into categories (id, name_ar, name_en, sort_order) values (gen_random_uuid(), 'التواصل والطلبات', 'Contact & Requests', 10);

-- =========================================================
-- 2) قاعدة المعرفة (150 سؤال)
-- =========================================================

-- تصنيف: عن رمال X / About Rimal X
with cat as (select id from categories where name_ar = 'عن رمال X' limit 1)
insert into knowledge_base (category_id, keywords_ar, keywords_en, question_ar, question_en, answer_ar, answer_en, citation_ar, citation_en, confidence)
values
  ((select id from cat), ARRAY['رمال', 'تعريف رمال']::text[], ARRAY['what is rimal', 'rimal']::text[], 'ما هي رمال X؟', 'What is Rimal X?', 'رمال X حاضنة ومسرّعة أعمال تقنية سعودية مقرها مدينة الطائف، تدعم رواد الأعمال من فكرة المشروع وحتى النمو والتوسع.', 'Rimal X is a Saudi tech business incubator and accelerator based in Taif, supporting entrepreneurs from the idea stage through growth and scale.', 'صفحة من نحن', 'About us page', 95),
  ((select id from cat), ARRAY['ماذا تقدم', 'خدمات']::text[], ARRAY['offer', 'services']::text[], 'ماذا تقدم رمال X؟', 'What does Rimal X offer?', 'تقدّم رمال X حاضنة أعمال، مسرّعة أعمال، مساحات عمل مشتركة وخاصة، دورات تدريبية، فعاليات، واستشارات متخصصة لرواد الأعمال والشركات الناشئة.', 'Rimal X offers a business incubator, an accelerator, shared and private workspaces, training courses, events, and specialized consulting for entrepreneurs and startups.', 'صفحة من نحن', 'About us page', 93),
  ((select id from cat), ARRAY['موقع', 'مقر', 'الطائف']::text[], ARRAY['location', 'based', 'taif']::text[], 'أين يقع مقر رمال X؟', 'Where is Rimal X located?', 'مقر رمال X الرئيسي في مدينة الطائف بالمملكة العربية السعودية.', 'Rimal X''s main headquarters is in Taif, Saudi Arabia.', 'صفحة من نحن', 'About us page', 95),
  ((select id from cat), ARRAY['شركة', 'حاضنة أعمال']::text[], ARRAY['company', 'incubator']::text[], 'هل رمال X شركة أم حاضنة أعمال؟', 'Is Rimal X a company or a business incubator?', 'رمال X هي حاضنة ومسرّعة أعمال تقنية متخصصة، وليست شركة تشغيلية تقدّم منتجًا واحدًا، بل منظومة دعم متكاملة لرواد الأعمال.', 'Rimal X is a specialized tech business incubator and accelerator, not a single-product operating company — it''s a full support ecosystem for entrepreneurs.', 'صفحة من نحن', 'About us page', 92),
  ((select id from cat), ARRAY['رؤية', 'رمال']::text[], ARRAY['vision', 'rimal']::text[], 'ما هي رؤية رمال X؟', 'What is Rimal X''s vision?', 'تتمثل رؤية رمال X في بناء منظومة ريادة أعمال تقنية مزدهرة في الطائف والمملكة، وتمكين رواد الأعمال من تحويل أفكارهم إلى مشاريع مستدامة.', 'Rimal X''s vision is to build a thriving tech entrepreneurship ecosystem in Taif and across the Kingdom, empowering entrepreneurs to turn ideas into sustainable ventures.', 'صفحة من نحن', 'About us page', 90),
  ((select id from cat), ARRAY['هدف', 'رمال']::text[], ARRAY['goal', 'mission']::text[], 'ما هو هدف رمال X؟', 'What is Rimal X''s goal?', 'هدف رمال X هو تسريع نمو المشاريع التقنية الناشئة عبر توفير الاحتضان والتسريع والمساحات والتدريب والاستشارات تحت مظلة واحدة.', 'Rimal X''s goal is to accelerate the growth of tech startups by providing incubation, acceleration, workspaces, training, and consulting under one roof.', 'صفحة من نحن', 'About us page', 90),
  ((select id from cat), ARRAY['لمن', 'خدمات']::text[], ARRAY['who', 'for', 'services']::text[], 'لمن تقدم رمال X خدماتها؟', 'Who are Rimal X''s services for?', 'خدمات رمال X موجّهة لرواد الأعمال الأفراد، الفرق الناشئة، والشركات الصغيرة والمتوسطة في القطاع التقني وما يتصل به.', 'Rimal X''s services are aimed at individual entrepreneurs, founding teams, and small-to-medium companies in the tech sector and related fields.', 'صفحة من نحن', 'About us page', 92),
  ((select id from cat), ARRAY['أفراد', 'خدمات']::text[], ARRAY['individuals', 'services']::text[], 'هل خدمات رمال X متاحة للأفراد؟', 'Are Rimal X''s services available to individuals?', 'نعم، يمكن للأفراد أصحاب الأفكار الاستفادة من خدمات رمال X مثل الحاضنة والدورات ومساحات العمل، وليس فقط الشركات المسجّلة.', 'Yes, individuals with an idea can use Rimal X''s services such as the incubator, courses, and workspaces — not only registered companies.', 'صفحة من نحن', 'About us page', 90),
  ((select id from cat), ARRAY['شركات', 'استفادة']::text[], ARRAY['companies', 'benefit']::text[], 'هل يمكن للشركات الاستفادة من خدماتكم؟', 'Can companies benefit from your services?', 'نعم، الشركات الناشئة والصغيرة يمكنها الاستفادة من المسرّعة، مساحات العمل، والاستشارات المتخصصة بحسب مرحلتها.', 'Yes, startups and small companies can benefit from the accelerator, workspaces, and specialized consulting depending on their stage.', 'صفحة من نحن', 'About us page', 90),
  ((select id from cat), ARRAY['السعودية فقط', 'تعملون']::text[], ARRAY['saudi arabia', 'only']::text[], 'هل تعملون داخل السعودية فقط؟', 'Do you operate only inside Saudi Arabia?', 'التركيز التشغيلي الحالي لرمال X داخل المملكة العربية السعودية، مع انفتاح على شراكات ومشاركين من خارجها في بعض البرامج والفعاليات.', 'Rimal X''s current operational focus is within Saudi Arabia, while remaining open to partnerships and participants from abroad in some programs and events.', 'صفحة من نحن', 'About us page', 88),
  ((select id from cat), ARRAY['تأسست', 'متى']::text[], ARRAY['founded', 'when']::text[], 'متى تأسست رمال X؟', 'When was Rimal X founded?', 'التاريخ الدقيق لتأسيس رمال X يحتاج تأكيدًا رسميًا من الفريق، لذلك يُفضّل التواصل المباشر للحصول على المعلومة الدقيقة.', 'The exact founding date of Rimal X needs official confirmation from the team, so please reach out directly for the precise information.', 'صفحة من نحن', 'About us page', 42),
  ((select id from cat), ARRAY['لماذا أختار', 'رمال']::text[], ARRAY['why choose', 'rimal']::text[], 'لماذا أختار رمال X؟', 'Why should I choose Rimal X?', 'لأن رمال X تجمع الاحتضان والتسريع ومساحات العمل والتدريب والاستشارات في منظومة واحدة متكاملة، مع تركيز محلي على بيئة الطائف وتيسير الوصول لفريق الدعم.', 'Because Rimal X brings incubation, acceleration, workspaces, training, and consulting together in one integrated ecosystem, with a local focus on the Taif environment and easy access to the support team.', 'صفحة من نحن', 'About us page', 88),
  ((select id from cat), ARRAY['يميز', 'عن غيرها']::text[], ARRAY['sets apart', 'different']::text[], 'ما الذي يميز رمال X عن غيرها؟', 'What sets Rimal X apart from others?', 'يميّز رمال X تكامل الخدمات تحت سقف واحد (احتضان، تسريع، مساحات، تدريب، استشارات)، إضافة إلى القرب من رواد الأعمال في الطائف والمناطق المجاورة.', 'What sets Rimal X apart is having incubation, acceleration, workspaces, training, and consulting integrated under one roof, plus close proximity to entrepreneurs in Taif and nearby areas.', 'صفحة من نحن', 'About us page', 88),
  ((select id from cat), ARRAY['مشاريع ناشئة', 'تدعمون']::text[], ARRAY['startups', 'support']::text[], 'هل تدعمون المشاريع الناشئة؟', 'Do you support startups?', 'نعم، دعم المشاريع الناشئة هو صميم عمل رمال X عبر برامج الحاضنة والمسرّعة تحديدًا.', 'Yes, supporting startups is at the core of what Rimal X does, specifically through the incubator and accelerator programs.', 'صفحة من نحن', 'About us page', 93),
  ((select id from cat), ARRAY['فريق استشاري']::text[], ARRAY['advisory team']::text[], 'هل لديكم فريق استشاري؟', 'Do you have an advisory team?', 'نعم، يتوفر لدى رمال X فريق ومستشارون يقدّمون الإرشاد لرواد الأعمال ضمن برامج الاحتضان والتسريع والاستشارات المباشرة.', 'Yes, Rimal X has a team of advisors who provide guidance to entrepreneurs through the incubation and acceleration programs and direct consulting.', 'صفحة من نحن', 'About us page', 88),
  ((select id from cat), ARRAY['زيارة', 'المقر']::text[], ARRAY['visit', 'office']::text[], 'هل يمكن زيارة المقر؟', 'Can I visit the office?', 'نعم، يمكن ترتيب زيارة لمقر رمال X في الطائف بالتنسيق المسبق مع الفريق.', 'Yes, a visit to Rimal X''s office in Taif can be arranged by coordinating with the team in advance.', 'صفحة من نحن', 'About us page', 85),
  ((select id from cat), ARRAY['ساعات العمل']::text[], ARRAY['working hours']::text[], 'ما هي ساعات العمل؟', 'What are the working hours?', 'ساعات العمل الدقيقة قد تختلف حسب اليوم والفعاليات، والأفضل التأكد منها مباشرة عبر قنوات التواصل قبل الزيارة.', 'Exact working hours may vary by day and by events, so it''s best to confirm directly through our contact channels before visiting.', 'صفحة من نحن', 'About us page', 45),
  ((select id from cat), ARRAY['كيف أتواصل']::text[], ARRAY['how to contact', 'contact you']::text[], 'كيف أتواصل معكم؟', 'How do I contact you?', 'يمكن التواصل مع رمال X عبر البريد الإلكتروني أو نموذج التواصل في الموقع، وسيقوم الفريق بالرد في أقرب وقت.', 'You can contact Rimal X via email or the contact form on the website, and the team will respond as soon as possible.', 'صفحة من نحن', 'About us page', 90),
  ((select id from cat), ARRAY['وسائل التواصل', 'حسابات']::text[], ARRAY['social media', 'accounts']::text[], 'هل لديكم حسابات على وسائل التواصل؟', 'Do you have social media accounts?', 'نعم، رمال X متواجدة على منصات التواصل الاجتماعي الرئيسية لمتابعة آخر الأخبار والفعاليات.', 'Yes, Rimal X is present on the main social media platforms for the latest news and events.', 'صفحة من نحن', 'About us page', 88),
  ((select id from cat), ARRAY['واتساب', 'رقم']::text[], ARRAY['whatsapp', 'number']::text[], 'هل يوجد رقم واتساب؟', 'Is there a WhatsApp number?', 'توفر قناة واتساب مباشرة يحتاج تأكيدًا من الفريق؛ الأضمن حاليًا هو التواصل عبر البريد الإلكتروني أو نموذج الموقع.', 'Availability of a direct WhatsApp channel needs confirmation from the team; for now, email or the website contact form is the most reliable option.', 'صفحة من نحن', 'About us page', 48);

-- تصنيف: حاضنة الأعمال / Business Incubator
with cat as (select id from categories where name_ar = 'حاضنة الأعمال' limit 1)
insert into knowledge_base (category_id, keywords_ar, keywords_en, question_ar, question_en, answer_ar, answer_en, citation_ar, citation_en, confidence)
values
  ((select id from cat), ARRAY['حاضنة الأعمال', 'تعريف الحاضنة']::text[], ARRAY['business incubator', 'what is incubator']::text[], 'ما هي حاضنة الأعمال؟', 'What is the business incubator?', 'حاضنة الأعمال في رمال X برنامج يدعم رواد الأعمال في المراحل المبكرة جدًا، من الفكرة حتى بناء نموذج عمل قابل للتنفيذ.', 'Rimal X''s business incubator is a program that supports entrepreneurs in the very early stages, from an idea to building a viable business model.', 'صفحة برنامج الحاضنة', 'Incubator program page', 93),
  ((select id from cat), ARRAY['الانضمام للحاضنة']::text[], ARRAY['join incubator']::text[], 'من يستطيع الانضمام للحاضنة؟', 'Who can join the incubator?', 'يمكن لأصحاب الأفكار ورواد الأعمال في المراحل المبكرة، أفرادًا أو فرقًا صغيرة، التقديم للانضمام إلى الحاضنة.', 'Individuals and small founding teams with early-stage ideas can apply to join the incubator.', 'صفحة برنامج الحاضنة', 'Incubator program page', 90),
  ((select id from cat), ARRAY['أقدم', 'الحاضنة']::text[], ARRAY['apply', 'incubator']::text[], 'كيف أقدم على الحاضنة؟', 'How do I apply to the incubator?', 'يتم التقديم على الحاضنة عبر تعبئة نموذج طلب الانضمام المتاح في الموقع أو بالتواصل المباشر مع فريق رمال X.', 'You apply to the incubator by filling out the application form available on the website or by contacting the Rimal X team directly.', 'صفحة برنامج الحاضنة', 'Incubator program page', 90),
  ((select id from cat), ARRAY['شروط القبول', 'حاضنة']::text[], ARRAY['admission conditions', 'incubator']::text[], 'ما شروط القبول؟', 'What are the admission conditions?', 'شروط القبول التفصيلية الدقيقة تُقيَّم حسب كل دفعة ومجال المشروع، والأفضل مراجعتها مباشرة مع فريق الحاضنة عند التقديم.', 'The exact detailed admission conditions are evaluated per cohort and project domain — best reviewed directly with the incubator team when applying.', 'صفحة برنامج الحاضنة', 'Incubator program page', 45),
  ((select id from cat), ARRAY['سجل تجاري', 'حاضنة']::text[], ARRAY['commercial registration']::text[], 'هل أحتاج إلى سجل تجاري؟', 'Do I need a commercial registration?', 'لا يُشترط عادة وجود سجل تجاري للانضمام في المراحل الأولى للحاضنة، لكن قد يُطلب لاحقًا حسب تقدّم المشروع.', 'A commercial registration usually isn''t required to join in the incubator''s early stages, though it may be requested later depending on project progress.', 'صفحة برنامج الحاضنة', 'Incubator program page', 50),
  ((select id from cat), ARRAY['نموذج أولي', 'حاضنة']::text[], ARRAY['prototype', 'incubator']::text[], 'هل أحتاج إلى نموذج أولي؟', 'Do I need a prototype?', 'لا يُشترط وجود نموذج أولي جاهز للانضمام للحاضنة؛ يكفي وجود فكرة واضحة قابلة للتطوير، ويساعدك البرنامج على بناء النموذج.', 'A ready prototype isn''t required to join the incubator; a clear, developable idea is enough, and the program helps you build the prototype.', 'صفحة برنامج الحاضنة', 'Incubator program page', 88),
  ((select id from cat), ARRAY['فترة الاحتضان', 'مدة']::text[], ARRAY['incubation period', 'duration']::text[], 'كم تستمر فترة الاحتضان؟', 'How long does the incubation period last?', 'مدة برنامج الاحتضان الدقيقة تختلف حسب المشروع والدفعة، وتُحدَّد بشكل نهائي مع فريق الحاضنة عند القبول.', 'The exact incubation period varies by project and cohort, and is finalized with the incubator team upon acceptance.', 'صفحة برنامج الحاضنة', 'Incubator program page', 48),
  ((select id from cat), ARRAY['يشمل', 'الاحتضان']::text[], ARRAY['includes', 'incubation']::text[], 'ماذا يشمل برنامج الاحتضان؟', 'What does the incubation program include?', 'يشمل برنامج الاحتضان الإرشاد من خبراء، مساحة عمل، ورش تطوير نموذج العمل، وربطًا بشبكة علاقات في القطاع التقني.', 'The incubation program includes mentorship from experts, workspace access, business model development workshops, and connections to the tech ecosystem.', 'صفحة برنامج الحاضنة', 'Incubator program page', 90),
  ((select id from cat), ARRAY['مرشدون', 'حاضنة']::text[], ARRAY['mentors', 'incubator']::text[], 'هل يوجد مرشدون؟', 'Are there mentors?', 'نعم، يرافق كل مشروع مرشدون ذوو خبرة يقدّمون التوجيه طوال فترة الاحتضان.', 'Yes, each project is paired with experienced mentors who provide guidance throughout the incubation period.', 'صفحة برنامج الحاضنة', 'Incubator program page', 90),
  ((select id from cat), ARRAY['استشارات', 'حاضنة']::text[], ARRAY['consulting', 'incubator']::text[], 'هل تقدمون استشارات؟', 'Do you provide consulting?', 'نعم، تقدَّم استشارات متنوعة (عمل، منتج، تسويق مبدئي) ضمن برنامج الحاضنة.', 'Yes, various consulting sessions (business, product, initial marketing) are offered as part of the incubator program.', 'صفحة برنامج الحاضنة', 'Incubator program page', 88),
  ((select id from cat), ARRAY['نموذج العمل', 'تطوير']::text[], ARRAY['business model', 'develop']::text[], 'هل تساعدون في تطوير نموذج العمل؟', 'Do you help develop the business model?', 'نعم، تطوير نموذج العمل (Business Model) هو من الأنشطة الأساسية داخل برنامج الحاضنة.', 'Yes, developing the business model is one of the core activities within the incubator program.', 'صفحة برنامج الحاضنة', 'Incubator program page', 90),
  ((select id from cat), ARRAY['خطة العمل', 'إعداد']::text[], ARRAY['business plan', 'prepare']::text[], 'هل تساعدون في إعداد خطة العمل؟', 'Do you help prepare a business plan?', 'نعم، يساعد فريق الحاضنة رواد الأعمال في إعداد خطة عمل واضحة ومنظّمة.', 'Yes, the incubator team helps entrepreneurs prepare a clear, well-structured business plan.', 'صفحة برنامج الحاضنة', 'Incubator program page', 88),
  ((select id from cat), ARRAY['دعم قانوني', 'حاضنة']::text[], ARRAY['legal support', 'incubator']::text[], 'هل يوجد دعم قانوني؟', 'Is there legal support?', 'يتوفر توجيه قانوني أساسي (مثل التأسيس والعقود) ضمن الحاضنة، أما الاستشارات القانونية المتخصصة فتُنسَّق بحسب الحاجة.', 'Basic legal guidance (such as incorporation and contracts) is available within the incubator, while specialized legal consulting is coordinated as needed.', 'صفحة برنامج الحاضنة', 'Incubator program page', 55),
  ((select id from cat), ARRAY['دعم مالي', 'حاضنة']::text[], ARRAY['financial support', 'incubator']::text[], 'هل يوجد دعم مالي؟', 'Is there financial support?', 'الدعم المالي المباشر (تمويل أو منح) في مرحلة الحاضنة يعتمد على المشروع وتوفره لا يكون مضمونًا لكل المشاركين؛ يُنسَّق مباشرة مع الفريق.', 'Direct financial support (funding or grants) at the incubation stage depends on the project and isn''t guaranteed for every participant; it''s coordinated directly with the team.', 'صفحة برنامج الحاضنة', 'Incubator program page', 42),
  ((select id from cat), ARRAY['الحاضنة مجانية']::text[], ARRAY['incubator free']::text[], 'هل الحاضنة مجانية؟', 'Is the incubator free?', 'تفاصيل الرسوم إن وُجدت تختلف حسب نوع البرنامج والخدمات المرافقة، والأدق تأكيدها مباشرة مع فريق رمال X عند التقديم.', 'Fee details, if any, vary by program type and accompanying services — best confirmed directly with the Rimal X team when applying.', 'صفحة برنامج الحاضنة', 'Incubator program page', 45),
  ((select id from cat), ARRAY['فكرة فقط', 'الانضمام']::text[], ARRAY['just an idea', 'join']::text[], 'هل أستطيع الانضمام بفكرة فقط؟', 'Can I join with just an idea?', 'نعم، يمكن الانضمام للحاضنة بفكرة واضحة فقط دون الحاجة لمنتج جاهز أو شركة مسجّلة.', 'Yes, you can join the incubator with just a clear idea, without needing a ready product or a registered company.', 'صفحة برنامج الحاضنة', 'Incubator program page', 90),
  ((select id from cat), ARRAY['أكثر من مشروع', 'احتضان']::text[], ARRAY['more than one project']::text[], 'هل يمكن احتضان أكثر من مشروع؟', 'Can more than one project be incubated?', 'الحاضنة تستقبل عدة مشاريع ضمن كل دفعة، لكن كل رائد أعمال أو فريق يُحتضَن مشروعًا واحدًا في نفس الوقت عادةً.', 'The incubator accepts multiple projects per cohort, but each entrepreneur or team is typically incubated for one project at a time.', 'صفحة برنامج الحاضنة', 'Incubator program page', 85),
  ((select id from cat), ARRAY['التقديم كفريق']::text[], ARRAY['apply as a team']::text[], 'هل يمكن التقديم كفريق؟', 'Can I apply as a team?', 'نعم، يمكن التقديم للحاضنة كفريق مؤسس وليس بالضرورة كفرد.', 'Yes, you can apply to the incubator as a founding team, not necessarily as an individual.', 'صفحة برنامج الحاضنة', 'Incubator program page', 90),
  ((select id from cat), ARRAY['رفض المشاريع', 'حاضنة']::text[], ARRAY['rejected projects', 'incubator']::text[], 'هل يتم رفض بعض المشاريع؟', 'Are some projects rejected?', 'نعم، تُقيَّم الطلبات وفق معايير الملاءمة والجاهزية، وقد لا يتم قبول بعض المشاريع في الدفعة الحالية.', 'Yes, applications are evaluated for fit and readiness, and some projects may not be accepted in the current cohort.', 'صفحة برنامج الحاضنة', 'Incubator program page', 85),
  ((select id from cat), ARRAY['نتيجة الطلب', 'حاضنة']::text[], ARRAY['application result']::text[], 'كيف أعرف نتيجة الطلب؟', 'How do I know the application result?', 'يتم إبلاغ المتقدمين بنتيجة طلبهم عبر البريد الإلكتروني أو وسيلة التواصل المسجّلة بعد انتهاء مرحلة التقييم.', 'Applicants are informed of their application result via email or their registered contact method after the evaluation stage ends.', 'صفحة برنامج الحاضنة', 'Incubator program page', 85);

-- تصنيف: مسرعة الأعمال / Business Accelerator
with cat as (select id from categories where name_ar = 'مسرعة الأعمال' limit 1)
insert into knowledge_base (category_id, keywords_ar, keywords_en, question_ar, question_en, answer_ar, answer_en, citation_ar, citation_en, confidence)
values
  ((select id from cat), ARRAY['مسرعة الأعمال', 'تعريف المسرعة']::text[], ARRAY['business accelerator', 'what is accelerator']::text[], 'ما هي مسرعة الأعمال؟', 'What is the business accelerator?', 'مسرّعة الأعمال في رمال X برنامج مكثف موجّه للشركات التي لديها منتج وعملاء أوائل، لتسريع نموها وتوسّعها.', 'Rimal X''s business accelerator is an intensive program for companies that already have a product and early customers, aimed at accelerating their growth and expansion.', 'صفحة برنامج المسرّعة', 'Accelerator program page', 93),
  ((select id from cat), ARRAY['الفرق', 'مسرعة', 'حاضنة']::text[], ARRAY['difference', 'accelerator', 'incubator']::text[], 'ما الفرق بين المسرعة والحاضنة؟', 'What''s the difference between the accelerator and the incubator?', 'الحاضنة موجّهة للأفكار في مراحلها الأولى، بينما المسرّعة موجّهة لشركات لديها منتج وعملاء فعليون وتريد تسريع النمو.', 'The incubator targets early-stage ideas, while the accelerator targets companies that already have a product and real customers and want to accelerate growth.', 'صفحة برنامج المسرّعة', 'Accelerator program page', 92),
  ((select id from cat), ARRAY['الانضمام للمسرعة']::text[], ARRAY['join accelerator']::text[], 'من يستطيع الانضمام للمسرعة؟', 'Who can join the accelerator?', 'الشركات الناشئة التي لديها منتج فعلي وعملاء أوائل يمكنها التقديم للانضمام إلى برنامج المسرّعة.', 'Startups that already have a real product and early customers can apply to join the accelerator program.', 'صفحة برنامج المسرّعة', 'Accelerator program page', 90),
  ((select id from cat), ARRAY['مدة البرنامج', 'مسرعة']::text[], ARRAY['program duration', 'accelerator']::text[], 'كم مدة البرنامج؟', 'How long is the program?', 'مدة برنامج المسرّعة الدقيقة تُحدَّد لكل دفعة وتُبلَّغ للشركات المقبولة عند بدء البرنامج.', 'The exact accelerator program duration is set per cohort and communicated to accepted companies when the program starts.', 'صفحة برنامج المسرّعة', 'Accelerator program page', 48),
  ((select id from cat), ARRAY['تدريب', 'مسرعة']::text[], ARRAY['training', 'accelerator']::text[], 'هل يوجد تدريب؟', 'Is there training?', 'نعم، يتضمن برنامج المسرّعة جلسات تدريبية مكثفة في النمو والتسويق والمبيعات والتشغيل.', 'Yes, the accelerator program includes intensive training sessions on growth, marketing, sales, and operations.', 'صفحة برنامج المسرّعة', 'Accelerator program page', 90),
  ((select id from cat), ARRAY['إرشاد', 'مسرعة']::text[], ARRAY['mentorship', 'accelerator']::text[], 'هل يوجد إرشاد؟', 'Is there mentorship?', 'نعم، تقترن كل شركة مشاركة بمرشدين متخصصين طوال فترة المسرّعة.', 'Yes, each participating company is paired with specialized mentors throughout the accelerator period.', 'صفحة برنامج المسرّعة', 'Accelerator program page', 90),
  ((select id from cat), ARRAY['الوصول للمستثمرين']::text[], ARRAY['access investors']::text[], 'هل تساعدون في الوصول للمستثمرين؟', 'Do you help access investors?', 'نعم، من أهداف المسرّعة ربط الشركات المشاركة بشبكة مستثمرين محتملين، خصوصًا قرب نهاية البرنامج.', 'Yes, one of the accelerator''s goals is connecting participating companies with a network of potential investors, especially near the end of the program.', 'صفحة برنامج المسرّعة', 'Accelerator program page', 88),
  ((select id from cat), ARRAY['التوسع', 'مسرعة']::text[], ARRAY['expansion', 'accelerator']::text[], 'هل تساعدون في التوسع؟', 'Do you help with expansion?', 'نعم، يركّز برنامج المسرّعة على مساعدة الشركات على التوسع في السوق وزيادة قاعدة العملاء.', 'Yes, the accelerator program focuses on helping companies expand in the market and grow their customer base.', 'صفحة برنامج المسرّعة', 'Accelerator program page', 88),
  ((select id from cat), ARRAY['التسويق', 'مسرعة']::text[], ARRAY['marketing', 'accelerator']::text[], 'هل تساعدون في التسويق؟', 'Do you help with marketing?', 'نعم، يشمل برنامج المسرّعة دعمًا في بناء استراتيجية التسويق والنمو.', 'Yes, the accelerator program includes support in building a marketing and growth strategy.', 'صفحة برنامج المسرّعة', 'Accelerator program page', 88),
  ((select id from cat), ARRAY['demo day']::text[], ARRAY['demo day']::text[], 'هل يوجد Demo Day؟', 'Is there a Demo Day?', 'نعم، يُختتم برنامج المسرّعة عادة بيوم عرض (Demo Day) تقدّم فيه الشركات مشاريعها أمام مستثمرين وشركاء محتملين.', 'Yes, the accelerator program typically ends with a Demo Day where companies pitch their projects to potential investors and partners.', 'صفحة برنامج المسرّعة', 'Accelerator program page', 88),
  ((select id from cat), ARRAY['البرنامج مجاني', 'مسرعة']::text[], ARRAY['program free', 'accelerator']::text[], 'هل البرنامج مجاني؟', 'Is the program free?', 'تفاصيل الرسوم أو أي مقابل حصص (Equity) في المسرّعة تختلف حسب البرنامج، وتُوضَّح بدقة عند القبول.', 'Fee details or any equity arrangement in the accelerator vary by program and are clarified precisely upon acceptance.', 'صفحة برنامج المسرّعة', 'Accelerator program page', 42),
  ((select id from cat), ARRAY['يشترط', 'شركة مسجلة']::text[], ARRAY['registered company required']::text[], 'هل يشترط وجود شركة؟', 'Is having a registered company required?', 'غالبًا يُفضَّل وجود كيان قانوني مسجَّل عند الانضمام للمسرّعة نظرًا لتقدّم مرحلة المشروع، لكن التفاصيل تُحسم مع فريق البرنامج.', 'A registered legal entity is generally preferred when joining the accelerator given the project''s advanced stage, but details are confirmed with the program team.', 'صفحة برنامج المسرّعة', 'Accelerator program page', 52),
  ((select id from cat), ARRAY['التقديم إلكترونيًا', 'مسرعة']::text[], ARRAY['apply online', 'accelerator']::text[], 'هل يمكن التقديم إلكترونيًا؟', 'Can I apply online?', 'نعم، يمكن تعبئة نموذج التقديم لبرنامج المسرّعة إلكترونيًا عبر الموقع.', 'Yes, the accelerator application form can be filled out online through the website.', 'صفحة برنامج المسرّعة', 'Accelerator program page', 88),
  ((select id from cat), ARRAY['مراحل البرنامج', 'مسرعة']::text[], ARRAY['program stages', 'accelerator']::text[], 'ما مراحل البرنامج؟', 'What are the program stages?', 'يمر برنامج المسرّعة عادة بمراحل: تقييم وقبول، تدريب وإرشاد مكثف، تحضير للاستثمار، ثم يوم العرض الختامي.', 'The accelerator program typically moves through stages: evaluation and acceptance, intensive training and mentorship, investment readiness, then the closing Demo Day.', 'صفحة برنامج المسرّعة', 'Accelerator program page', 85),
  ((select id from cat), ARRAY['اختيار الشركات', 'مسرعة']::text[], ARRAY['company selection', 'accelerator']::text[], 'كيف يتم اختيار الشركات؟', 'How are companies selected?', 'يتم اختيار الشركات المشاركة في المسرّعة بناءً على جاهزية المنتج، وجود عملاء فعليين، وإمكانية النمو والتوسع.', 'Companies are selected for the accelerator based on product readiness, existence of real customers, and growth/scale potential.', 'صفحة برنامج المسرّعة', 'Accelerator program page', 85);

-- تصنيف: مساحات العمل / Workspaces
with cat as (select id from categories where name_ar = 'مساحات العمل' limit 1)
insert into knowledge_base (category_id, keywords_ar, keywords_en, question_ar, question_en, answer_ar, answer_en, citation_ar, citation_en, confidence)
values
  ((select id from cat), ARRAY['أحجز', 'مساحة عمل']::text[], ARRAY['book a workspace', 'workspace']::text[], 'كيف أحجز مساحة عمل؟', 'How do I book a workspace?', 'يمكن حجز مساحة العمل عبر الموقع الإلكتروني أو بالتواصل المباشر مع فريق رمال X لتحديد النوع والموعد المناسبين.', 'You can book a workspace through the website or by contacting the Rimal X team directly to choose the right type and time.', 'صفحة مساحات العمل', 'Workspaces page', 90),
  ((select id from cat), ARRAY['أنواع المساحات', 'مساحات العمل المتوفرة']::text[], ARRAY['workspace types', 'workspaces are available']::text[], 'ما أنواع المساحات؟', 'What workspace types are available?', 'تشمل أنواع المساحات: مقعد مرن (Hot Desk)، مكتب مخصص (Dedicated Desk)، مكتب خاص (Private Office)، وقاعات اجتماعات وتدريب.', 'Workspace types include a Hot Desk, a Dedicated Desk, a Private Office, and meeting/training rooms.', 'صفحة مساحات العمل', 'Workspaces page', 93),
  ((select id from cat), ARRAY['مكاتب خاصة']::text[], ARRAY['private offices']::text[], 'هل يوجد مكاتب خاصة؟', 'Are there private offices?', 'نعم، تتوفر مكاتب خاصة (Private Office) للفرق والشركات التي تحتاج مساحة مغلقة مستقلة.', 'Yes, private offices are available for teams and companies that need an enclosed, independent space.', 'صفحة مساحات العمل', 'Workspaces page', 92),
  ((select id from cat), ARRAY['مكاتب مشتركة']::text[], ARRAY['shared desks']::text[], 'هل يوجد مكاتب مشتركة؟', 'Are there shared desks?', 'نعم، تتوفر مساحات مشتركة (Hot Desk / Dedicated Desk) مناسبة للأفراد ورواد الأعمال المستقلين.', 'Yes, shared spaces (Hot Desk / Dedicated Desk) are available, suitable for individuals and independent entrepreneurs.', 'صفحة مساحات العمل', 'Workspaces page', 92),
  ((select id from cat), ARRAY['قاعات اجتماعات']::text[], ARRAY['meeting rooms']::text[], 'هل توجد قاعات اجتماعات؟', 'Are there meeting rooms?', 'نعم، تتوفر قاعات اجتماعات مجهّزة يمكن حجزها بالساعة.', 'Yes, equipped meeting rooms are available and can be booked by the hour.', 'صفحة مساحات العمل', 'Workspaces page', 93),
  ((select id from cat), ARRAY['قاعات تدريب']::text[], ARRAY['training halls']::text[], 'هل توجد قاعات تدريب؟', 'Are there training halls?', 'نعم، تتوفر قاعات تدريب وفعاليات مناسبة للورش والدورات والجلسات الجماعية.', 'Yes, training and event halls are available, suitable for workshops, courses, and group sessions.', 'صفحة مساحات العمل', 'Workspaces page', 90),
  ((select id from cat), ARRAY['لاونج vip']::text[], ARRAY['vip lounge']::text[], 'هل يوجد لاونج VIP؟', 'Is there a VIP lounge?', 'توفر لاونج VIP مخصص يحتاج تأكيدًا من الفريق حسب الفرع والمرافق المتاحة حاليًا.', 'Availability of a dedicated VIP lounge needs confirmation from the team depending on the branch and currently available facilities.', 'صفحة مساحات العمل', 'Workspaces page', 45),
  ((select id from cat), ARRAY['الإنترنت متوفر']::text[], ARRAY['internet available']::text[], 'هل الإنترنت متوفر؟', 'Is internet available?', 'نعم، تتوفر خدمة إنترنت عالية السرعة في جميع مساحات العمل.', 'Yes, high-speed internet is available across all workspaces.', 'صفحة مساحات العمل', 'Workspaces page', 93),
  ((select id from cat), ARRAY['طباعة', 'مساحة']::text[], ARRAY['printing']::text[], 'هل يوجد طباعة؟', 'Is printing available?', 'تتوفر خدمة طباعة أساسية داخل مساحات العمل، وتفاصيل التكلفة إن وُجدت تُحدَّد عند الاستخدام.', 'Basic printing service is available within the workspaces, with any cost details determined at time of use.', 'صفحة مساحات العمل', 'Workspaces page', 50),
  ((select id from cat), ARRAY['مواقف سيارات']::text[], ARRAY['parking']::text[], 'هل يوجد مواقف سيارات؟', 'Is there parking?', 'تتوفر مواقف سيارات قريبة من مقر رمال X، وتفاصيل السعة الدقيقة تُنسَّق مع الفريق عند الزيارة.', 'Parking is available near the Rimal X premises, with exact capacity details coordinated with the team upon visiting.', 'صفحة مساحات العمل', 'Workspaces page', 48),
  ((select id from cat), ARRAY['الحجز بالساعة']::text[], ARRAY['book by the hour']::text[], 'هل يمكن الحجز بالساعة؟', 'Can I book by the hour?', 'نعم، يمكن حجز بعض المساحات مثل قاعات الاجتماعات بالساعة، بجانب خيارات الاشتراك الشهري.', 'Yes, some spaces like meeting rooms can be booked by the hour, alongside monthly subscription options.', 'صفحة مساحات العمل', 'Workspaces page', 90),
  ((select id from cat), ARRAY['اشتراك شهري']::text[], ARRAY['monthly subscription']::text[], 'هل يوجد اشتراك شهري؟', 'Is there a monthly subscription?', 'نعم، تتوفر باقات اشتراك شهري لمساحات العمل المختلفة (Hot Desk، Dedicated Desk، Private Office).', 'Yes, monthly subscription packages are available for the different workspace types (Hot Desk, Dedicated Desk, Private Office).', 'صفحة مساحات العمل', 'Workspaces page', 90),
  ((select id from cat), ARRAY['إلغاء الحجز']::text[], ARRAY['cancel booking']::text[], 'هل أستطيع إلغاء الحجز؟', 'Can I cancel my booking?', 'يمكن إلغاء الحجز عادة قبل الموعد بفترة كافية، وسياسة الإلغاء الدقيقة (المهل والاسترجاع) تُحدَّد عند الحجز.', 'Bookings can generally be cancelled with sufficient advance notice, and the exact cancellation policy (deadlines and refunds) is specified at time of booking.', 'صفحة مساحات العمل', 'Workspaces page', 45),
  ((select id from cat), ARRAY['تعديل موعد الحجز']::text[], ARRAY['reschedule booking']::text[], 'هل يمكن تعديل موعد الحجز؟', 'Can I reschedule my booking?', 'نعم، يمكن طلب تعديل موعد الحجز بالتواصل مع فريق رمال X مسبقًا حسب التوفر.', 'Yes, you can request to reschedule a booking by contacting the Rimal X team in advance, subject to availability.', 'صفحة مساحات العمل', 'Workspaces page', 85),
  ((select id from cat), ARRAY['خصومات', 'مساحة']::text[], ARRAY['discounts']::text[], 'هل يوجد خصومات؟', 'Are there discounts?', 'قد تتوفر خصومات موسمية أو لمشتركي برامج الحاضنة/المسرّعة، وتفاصيلها الدقيقة تُعلَن بشكل دوري.', 'Seasonal discounts or discounts for incubator/accelerator members may be available, with exact details announced periodically.', 'صفحة مساحات العمل', 'Workspaces page', 48),
  ((select id from cat), ARRAY['حجز الشركات']::text[], ARRAY['companies book']::text[], 'هل يمكن للشركات الحجز؟', 'Can companies book?', 'نعم، يمكن للشركات حجز مساحات عمل أو مكاتب خاصة لفرقها بشكل مستمر أو مؤقت.', 'Yes, companies can book workspaces or private offices for their teams, either ongoing or temporary.', 'صفحة مساحات العمل', 'Workspaces page', 90),
  ((select id from cat), ARRAY['استقبال العملاء']::text[], ARRAY['host clients']::text[], 'هل يمكن استقبال العملاء؟', 'Can I host clients?', 'نعم، يمكن استقبال العملاء والزوار داخل مساحات العمل وقاعات الاجتماعات المخصصة لذلك.', 'Yes, clients and visitors can be hosted within the workspaces and meeting rooms designated for that.', 'صفحة مساحات العمل', 'Workspaces page', 88),
  ((select id from cat), ARRAY['دخول 24 ساعة']::text[], ARRAY['24-hour access']::text[], 'هل يوجد دخول 24 ساعة؟', 'Is 24-hour access available?', 'توفر دخول على مدار الساعة يحتاج تأكيدًا من الفريق حسب نوع الاشتراك والفرع.', 'Availability of 24-hour access needs confirmation from the team depending on subscription type and branch.', 'صفحة مساحات العمل', 'Workspaces page', 45),
  ((select id from cat), ARRAY['أدفع', 'رسوم الحجز']::text[], ARRAY['pay', 'booking fees']::text[], 'كيف أدفع رسوم الحجز؟', 'How do I pay the booking fees?', 'تتم عملية الدفع عادة عبر وسائل الدفع الإلكتروني المتاحة في نموذج الحجز أو بالتنسيق المباشر مع الفريق.', 'Payment is usually made via the electronic payment methods available in the booking form or by direct coordination with the team.', 'صفحة مساحات العمل', 'Workspaces page', 85),
  ((select id from cat), ARRAY['زيارة المساحات', 'قبل الحجز']::text[], ARRAY['visit before booking']::text[], 'هل يمكن زيارة المساحات قبل الحجز؟', 'Can I visit the space before booking?', 'نعم، يمكن ترتيب جولة على مساحات العمل قبل اتخاذ قرار الحجز.', 'Yes, a tour of the workspaces can be arranged before making a booking decision.', 'صفحة مساحات العمل', 'Workspaces page', 88);

-- تصنيف: الدورات التدريبية / Training Courses
with cat as (select id from categories where name_ar = 'الدورات التدريبية' limit 1)
insert into knowledge_base (category_id, keywords_ar, keywords_en, question_ar, question_en, answer_ar, answer_en, citation_ar, citation_en, confidence)
values
  ((select id from cat), ARRAY['الدورات المتوفرة']::text[], ARRAY['available courses', 'courses are available']::text[], 'ما الدورات المتوفرة؟', 'What courses are available?', 'تقدّم رمال X دورات في ريادة الأعمال والمهارات التقنية والتسويق وتطوير المنتجات، وتُحدَّث القائمة دوريًا.', 'Rimal X offers courses in entrepreneurship, tech skills, marketing, and product development, with the list updated periodically.', 'صفحة الدورات التدريبية', 'Training courses page', 90),
  ((select id from cat), ARRAY['تسجيل دورة']::text[], ARRAY['register course']::text[], 'كيف أسجل في دورة؟', 'How do I register for a course?', 'يتم التسجيل في الدورات عبر نموذج التسجيل الخاص بكل دورة على الموقع.', 'Course registration is done via the specific registration form for each course on the website.', 'صفحة الدورات التدريبية', 'Training courses page', 90),
  ((select id from cat), ARRAY['الدورات مجانية']::text[], ARRAY['courses free']::text[], 'هل الدورات مجانية؟', 'Are the courses free?', 'بعض الدورات مجانية وأخرى برسوم رمزية، وتفاصيل كل دورة تُذكَر عند فتح التسجيل لها.', 'Some courses are free while others have a nominal fee, with details for each course mentioned when registration opens.', 'صفحة الدورات التدريبية', 'Training courses page', 50),
  ((select id from cat), ARRAY['رسوم دورة', 'قيمة الرسوم']::text[], ARRAY['course fees', 'fee amount']::text[], 'هل يوجد رسوم؟', 'Are there fees?', 'قيمة الرسوم إن وُجدت تختلف من دورة لأخرى، وتُوضَّح بدقة في صفحة كل دورة عند فتح التسجيل.', 'Fee amounts, if any, vary from course to course and are stated precisely on each course''s page when registration opens.', 'صفحة الدورات التدريبية', 'Training courses page', 45),
  ((select id from cat), ARRAY['شهادة', 'دورة']::text[], ARRAY['certificate', 'course']::text[], 'هل أحصل على شهادة؟', 'Do I get a certificate?', 'نعم، يحصل المشاركون على شهادة حضور أو إتمام عند إنهاء أغلب الدورات التدريبية.', 'Yes, participants receive an attendance or completion certificate upon finishing most training courses.', 'صفحة الدورات التدريبية', 'Training courses page', 88),
  ((select id from cat), ARRAY['شهادات معتمدة']::text[], ARRAY['accredited certificates']::text[], 'هل الشهادات معتمدة؟', 'Are the certificates accredited?', 'درجة الاعتماد الرسمي للشهادة تختلف حسب نوع الدورة والجهة المنظِّمة، والأدق تأكيدها عند التسجيل في كل دورة.', 'The certificate''s level of official accreditation varies by course type and organizing body — best confirmed at registration for each course.', 'صفحة الدورات التدريبية', 'Training courses page', 42),
  ((select id from cat), ARRAY['دورات حضورية']::text[], ARRAY['in-person courses']::text[], 'هل الدورات حضورية؟', 'Are the courses in-person?', 'تُقدَّم أغلب دورات رمال X حضوريًا في مقرها بالطائف، مع إمكانية توفر بعضها عن بعد.', 'Most Rimal X courses are delivered in-person at its Taif location, with some potentially available remotely.', 'صفحة الدورات التدريبية', 'Training courses page', 85),
  ((select id from cat), ARRAY['دورات عن بعد']::text[], ARRAY['remote courses']::text[], 'هل توجد دورات عن بعد؟', 'Are there remote courses?', 'قد تُطرح بعض الدورات عن بعد حسب طبيعة المحتوى والفئة المستهدفة، وتُعلَن ضمن تفاصيل كل دورة.', 'Some courses may be offered remotely depending on the content and target audience, announced within each course''s details.', 'صفحة الدورات التدريبية', 'Training courses page', 55),
  ((select id from cat), ARRAY['إعادة مشاهدة']::text[], ARRAY['rewatch course']::text[], 'هل يمكن إعادة مشاهدة الدورة؟', 'Can I rewatch the course?', 'توفر إعادة المشاهدة يعتمد على ما إذا كانت الدورة مسجَّلة أو مباشرة بالكامل، ويُذكَر ذلك في تفاصيل الدورة.', 'Availability of rewatching depends on whether the course is recorded or fully live, and this is mentioned in the course details.', 'صفحة الدورات التدريبية', 'Training courses page', 48),
  ((select id from cat), ARRAY['حد للعمر']::text[], ARRAY['age limit']::text[], 'هل يوجد حد للعمر؟', 'Is there an age limit?', 'الحد الأدنى للعمر إن وُجد يختلف حسب طبيعة الدورة، ويُذكَر صراحة في متطلبات كل دورة عند فتح التسجيل.', 'A minimum age requirement, if any, varies by course and is explicitly stated in each course''s requirements when registration opens.', 'صفحة الدورات التدريبية', 'Training courses page', 45),
  ((select id from cat), ARRAY['خبرة', 'دورة']::text[], ARRAY['experience', 'course']::text[], 'هل تحتاج خبرة؟', 'Do I need prior experience?', 'أغلب الدورات التمهيدية لا تشترط خبرة سابقة، بينما قد تتطلب بعض الدورات المتقدمة خلفية معيّنة تُذكَر في وصفها.', 'Most introductory courses don''t require prior experience, while some advanced courses may require a specific background stated in their description.', 'صفحة الدورات التدريبية', 'Training courses page', 80),
  ((select id from cat), ARRAY['مشاريع عملية']::text[], ARRAY['hands-on projects']::text[], 'هل يوجد مشاريع عملية؟', 'Are there hands-on projects?', 'نعم، تتضمن العديد من الدورات تطبيقات ومشاريع عملية لتثبيت المهارات المكتسبة.', 'Yes, many courses include practical applications and hands-on projects to reinforce the skills learned.', 'صفحة الدورات التدريبية', 'Training courses page', 85),
  ((select id from cat), ARRAY['إلغاء التسجيل', 'دورة']::text[], ARRAY['cancel registration', 'course']::text[], 'هل يمكن إلغاء التسجيل؟', 'Can I cancel my course registration?', 'نعم، يمكن إلغاء التسجيل في الدورة قبل بدايتها وفق سياسة الإلغاء الخاصة بكل دورة.', 'Yes, you can cancel a course registration before it starts, per that course''s specific cancellation policy.', 'صفحة الدورات التدريبية', 'Training courses page', 80),
  ((select id from cat), ARRAY['مواعيد الدورات']::text[], ARRAY['course schedules']::text[], 'كيف أعرف مواعيد الدورات؟', 'How do I know course schedules?', 'تُعلَن مواعيد الدورات القادمة على الموقع وحسابات التواصل الاجتماعي الخاصة برمال X.', 'Upcoming course schedules are announced on the website and Rimal X''s social media accounts.', 'صفحة الدورات التدريبية', 'Training courses page', 88),
  ((select id from cat), ARRAY['تسجيل موظفين', 'دورة']::text[], ARRAY['register employees', 'course']::text[], 'هل يمكن للشركات تسجيل موظفيها؟', 'Can companies register their employees?', 'نعم، يمكن للشركات تسجيل عدد من موظفيها دفعة واحدة في الدورات التدريبية المناسبة.', 'Yes, companies can register a number of their employees at once for suitable training courses.', 'صفحة الدورات التدريبية', 'Training courses page', 85);

-- تصنيف: الفعاليات / Events
with cat as (select id from categories where name_ar = 'الفعاليات' limit 1)
insert into knowledge_base (category_id, keywords_ar, keywords_en, question_ar, question_en, answer_ar, answer_en, citation_ar, citation_en, confidence)
values
  ((select id from cat), ARRAY['الفعاليات القادمة']::text[], ARRAY['upcoming events']::text[], 'كيف أعرف الفعاليات القادمة؟', 'How do I know about upcoming events?', 'تُنشر الفعاليات القادمة على موقع رمال X وحساباتها على وسائل التواصل الاجتماعي.', 'Upcoming events are published on the Rimal X website and its social media accounts.', 'صفحة الفعاليات', 'Events page', 88),
  ((select id from cat), ARRAY['تسجيل فعالية']::text[], ARRAY['register event']::text[], 'كيف أسجل في فعالية؟', 'How do I register for an event?', 'يتم التسجيل في الفعاليات عبر نموذج تسجيل مخصص لكل فعالية يُنشر مع الإعلان عنها.', 'Event registration is done via a dedicated registration form for each event, published alongside its announcement.', 'صفحة الفعاليات', 'Events page', 88),
  ((select id from cat), ARRAY['الفعاليات مجانية']::text[], ARRAY['events free']::text[], 'هل الفعاليات مجانية؟', 'Are the events free?', 'أغلب فعاليات رمال X مجانية، وبعضها قد يكون برسوم رمزية حسب نوع الفعالية.', 'Most Rimal X events are free, and some may have a nominal fee depending on the event type.', 'صفحة الفعاليات', 'Events page', 82),
  ((select id from cat), ARRAY['عدد محدود', 'فعالية']::text[], ARRAY['limited seats', 'event']::text[], 'هل يوجد عدد محدود؟', 'Is there a limited number of seats?', 'نعم، عدد المقاعد في أغلب الفعاليات محدود، ويُنصح بالتسجيل المبكر.', 'Yes, seats at most events are limited, and early registration is recommended.', 'صفحة الفعاليات', 'Events page', 82),
  ((select id from cat), ARRAY['إلغاء التسجيل', 'فعالية']::text[], ARRAY['cancel registration', 'event']::text[], 'هل يمكن إلغاء التسجيل؟', 'Can I cancel my event registration?', 'نعم، يمكن إلغاء التسجيل في الفعالية قبل موعدها لإتاحة المقعد لغيرك.', 'Yes, you can cancel your event registration before it starts to free the seat for someone else.', 'صفحة الفعاليات', 'Events page', 85),
  ((select id from cat), ARRAY['ورش عمل']::text[], ARRAY['workshops']::text[], 'هل توجد ورش عمل؟', 'Are there workshops?', 'نعم، تنظّم رمال X ورش عمل تفاعلية ضمن فعالياتها الدورية.', 'Yes, Rimal X organizes interactive workshops as part of its regular events.', 'صفحة الفعاليات', 'Events page', 88),
  ((select id from cat), ARRAY['هاكاثونات']::text[], ARRAY['hackathons']::text[], 'هل يوجد هاكاثونات؟', 'Are there hackathons?', 'نعم، تستضيف رمال X هاكاثونات من حين لآخر لتشجيع الابتكار والحلول التقنية السريعة.', 'Yes, Rimal X hosts hackathons from time to time to encourage innovation and rapid tech solutions.', 'صفحة الفعاليات', 'Events page', 85),
  ((select id from cat), ARRAY['مؤتمرات']::text[], ARRAY['conferences']::text[], 'هل تقدمون مؤتمرات؟', 'Do you hold conferences?', 'نعم، تشارك رمال X أو تنظّم مؤتمرات ولقاءات متخصصة في ريادة الأعمال والتقنية.', 'Yes, Rimal X participates in or organizes conferences and specialized gatherings on entrepreneurship and tech.', 'صفحة الفعاليات', 'Events page', 82),
  ((select id from cat), ARRAY['شهادات', 'فعالية']::text[], ARRAY['certificates', 'event']::text[], 'هل يحصل المشاركون على شهادات؟', 'Do participants get certificates?', 'بعض الفعاليات مثل الورش والهاكاثونات تمنح المشاركين شهادة مشاركة، ويُذكَر ذلك عند الإعلان عنها.', 'Some events like workshops and hackathons grant participants a certificate of participation, mentioned when the event is announced.', 'صفحة الفعاليات', 'Events page', 65),
  ((select id from cat), ARRAY['اقتراح فعالية']::text[], ARRAY['suggest event']::text[], 'هل يمكن اقتراح فعالية؟', 'Can I suggest an event?', 'نعم، يمكن اقتراح أفكار فعاليات جديدة بالتواصل مع فريق رمال X.', 'Yes, you can suggest new event ideas by contacting the Rimal X team.', 'صفحة الفعاليات', 'Events page', 85);

-- تصنيف: القطاعات المستهدفة / Target Sectors
with cat as (select id from categories where name_ar = 'القطاعات المستهدفة' limit 1)
insert into knowledge_base (category_id, keywords_ar, keywords_en, question_ar, question_en, answer_ar, answer_en, citation_ar, citation_en, confidence)
values
  ((select id from cat), ARRAY['القطاعات التي تدعمونها']::text[], ARRAY['sectors supported']::text[], 'ما القطاعات التي تدعمونها؟', 'What sectors do you support?', 'تدعم رمال X بشكل أساسي المشاريع التقنية وما يتصل بها، مع انفتاح على قطاعات متعددة ذات طابع مبتكر.', 'Rimal X primarily supports tech-related projects and adjacent fields, while remaining open to multiple innovation-driven sectors.', 'صفحة القطاعات المستهدفة', 'Target sectors page', 88),
  ((select id from cat), ARRAY['مشاريع تقنية']::text[], ARRAY['tech projects']::text[], 'هل تدعمون المشاريع التقنية؟', 'Do you support tech projects?', 'نعم، المشاريع التقنية هي التركيز الأساسي لبرامج رمال X.', 'Yes, tech projects are the core focus of Rimal X''s programs.', 'صفحة القطاعات المستهدفة', 'Target sectors page', 93),
  ((select id from cat), ARRAY['الذكاء الاصطناعي']::text[], ARRAY['artificial intelligence']::text[], 'هل تدعمون الذكاء الاصطناعي؟', 'Do you support AI?', 'نعم، مشاريع الذكاء الاصطناعي مرحّب بها ضمن القطاعات التقنية التي تدعمها رمال X.', 'Yes, AI projects are welcome among the tech sectors Rimal X supports.', 'صفحة القطاعات المستهدفة', 'Target sectors page', 90),
  ((select id from cat), ARRAY['إنترنت الأشياء']::text[], ARRAY['internet of things', 'iot']::text[], 'هل تدعمون إنترنت الأشياء؟', 'Do you support IoT?', 'نعم، مشاريع إنترنت الأشياء (IoT) تندرج ضمن القطاعات التقنية المدعومة.', 'Yes, Internet of Things (IoT) projects fall within the supported tech sectors.', 'صفحة القطاعات المستهدفة', 'Target sectors page', 88),
  ((select id from cat), ARRAY['تطبيقات', 'دعم']::text[], ARRAY['apps', 'support']::text[], 'هل تدعمون التطبيقات؟', 'Do you support apps?', 'نعم، تطوير التطبيقات (جوال وويب) من المجالات المدعومة بشكل واسع.', 'Yes, app development (mobile and web) is a widely supported area.', 'صفحة القطاعات المستهدفة', 'Target sectors page', 90),
  ((select id from cat), ARRAY['التجارة الإلكترونية']::text[], ARRAY['e-commerce']::text[], 'هل تدعمون التجارة الإلكترونية؟', 'Do you support e-commerce?', 'نعم، مشاريع التجارة الإلكترونية مدعومة ضمن القطاعات التقنية والتجارية.', 'Yes, e-commerce projects are supported within the tech and commerce sectors.', 'صفحة القطاعات المستهدفة', 'Target sectors page', 88),
  ((select id from cat), ARRAY['الزراعة الذكية']::text[], ARRAY['smart agriculture']::text[], 'هل تدعمون الزراعة الذكية؟', 'Do you support smart agriculture?', 'نعم، مشاريع الزراعة الذكية التي تعتمد على حلول تقنية مرحّب بها ضمن نطاق الدعم.', 'Yes, smart agriculture projects built on tech solutions are welcome within the scope of support.', 'صفحة القطاعات المستهدفة', 'Target sectors page', 82),
  ((select id from cat), ARRAY['السياحة', 'دعم']::text[], ARRAY['tourism', 'support']::text[], 'هل تدعمون السياحة؟', 'Do you support tourism?', 'نعم، مشاريع السياحة والضيافة ذات الطابع التقني تدخل ضمن القطاعات المدعومة، خصوصًا لملاءمتها لبيئة الطائف.', 'Yes, tech-driven tourism and hospitality projects fall within the supported sectors, especially given their fit with the Taif environment.', 'صفحة القطاعات المستهدفة', 'Target sectors page', 82),
  ((select id from cat), ARRAY['التصنيع', 'دعم']::text[], ARRAY['manufacturing', 'support']::text[], 'هل تدعمون التصنيع؟', 'Do you support manufacturing?', 'مشاريع التصنيع ذات المكوّن التقني (مثل الأتمتة) قد تدخل ضمن النطاق، وتُقيَّم كل حالة على حدة.', 'Manufacturing projects with a tech component (like automation) may fall within scope, evaluated on a case-by-case basis.', 'صفحة القطاعات المستهدفة', 'Target sectors page', 55),
  ((select id from cat), ARRAY['البرمجيات', 'دعم']::text[], ARRAY['software', 'support']::text[], 'هل تدعمون البرمجيات؟', 'Do you support software?', 'نعم، مشاريع البرمجيات من أبرز المجالات المدعومة في رمال X.', 'Yes, software projects are among the most prominent supported areas at Rimal X.', 'صفحة القطاعات المستهدفة', 'Target sectors page', 93),
  ((select id from cat), ARRAY['مشاريع saas']::text[], ARRAY['saas projects']::text[], 'هل تدعمون مشاريع SaaS؟', 'Do you support SaaS projects?', 'نعم، مشاريع SaaS مدعومة بقوة ضمن قطاع البرمجيات والتقنية.', 'Yes, SaaS projects are strongly supported within the software and tech sector.', 'صفحة القطاعات المستهدفة', 'Target sectors page', 90),
  ((select id from cat), ARRAY['الأمن السيبراني']::text[], ARRAY['cybersecurity']::text[], 'هل تدعمون الأمن السيبراني؟', 'Do you support cybersecurity?', 'نعم، مشاريع الأمن السيبراني من القطاعات التقنية المدعومة.', 'Yes, cybersecurity projects are among the supported tech sectors.', 'صفحة القطاعات المستهدفة', 'Target sectors page', 88),
  ((select id from cat), ARRAY['مشروع متعدد المجالات']::text[], ARRAY['multi-sector project']::text[], 'هل يمكن قبول مشروع متعدد المجالات؟', 'Can a multi-sector project be accepted?', 'نعم، يمكن قبول مشاريع تجمع بين أكثر من مجال طالما لها مكوّن تقني واضح.', 'Yes, projects spanning more than one field can be accepted as long as they have a clear tech component.', 'صفحة القطاعات المستهدفة', 'Target sectors page', 82),
  ((select id from cat), ARRAY['قطاعات غير مدعومة']::text[], ARRAY['unsupported sectors']::text[], 'هل يوجد قطاعات غير مدعومة؟', 'Are there unsupported sectors?', 'القائمة الدقيقة للقطاعات المستثناة إن وُجدت تُحدَّد حسب سياسة القبول الحالية، والأفضل التأكد منها عند التقديم.', 'The exact list of excluded sectors, if any, depends on the current admission policy — best confirmed when applying.', 'صفحة القطاعات المستهدفة', 'Target sectors page', 45),
  ((select id from cat), ARRAY['مشروعي مناسب']::text[], ARRAY['project fit']::text[], 'كيف أعرف إذا كان مشروعي مناسبًا؟', 'How do I know if my project is a good fit?', 'أفضل طريقة هي التقديم مباشرة أو التواصل مع فريق رمال X لمراجعة فكرتك وتقييم مدى ملاءمتها للبرامج المتاحة.', 'The best way is to apply directly or contact the Rimal X team to review your idea and assess its fit with the available programs.', 'صفحة القطاعات المستهدفة', 'Target sectors page', 85);

-- تصنيف: الدعم والاستشارات / Support & Consulting
with cat as (select id from categories where name_ar = 'الدعم والاستشارات' limit 1)
insert into knowledge_base (category_id, keywords_ar, keywords_en, question_ar, question_en, answer_ar, answer_en, citation_ar, citation_en, confidence)
values
  ((select id from cat), ARRAY['أحجز استشارة']::text[], ARRAY['book consultation']::text[], 'كيف أحجز استشارة؟', 'How do I book a consultation?', 'يمكن حجز استشارة عبر نموذج طلب الاستشارات في الموقع أو بالتواصل المباشر مع فريق رمال X.', 'You can book a consultation via the consulting request form on the website or by contacting the Rimal X team directly.', 'صفحة الدعم والاستشارات', 'Support & consulting page', 88),
  ((select id from cat), ARRAY['الاستشارة مجانية']::text[], ARRAY['consultation free']::text[], 'هل الاستشارة مجانية؟', 'Is the consultation free?', 'تتوفر جلسات استشارية أولية مجانية في الغالب، بينما قد تكون الجلسات المتخصصة المطوّلة برسوم تُوضَّح مسبقًا.', 'Initial consultation sessions are mostly free, while longer specialized sessions may carry fees clarified in advance.', 'صفحة الدعم والاستشارات', 'Support & consulting page', 48),
  ((select id from cat), ARRAY['المستشارون']::text[], ARRAY['consultants']::text[], 'من هم المستشارون؟', 'Who are the consultants?', 'المستشارون فريق من الخبراء والمرشدين المتعاونين مع رمال X في مجالات الأعمال والتقنية والتسويق والتمويل.', 'The consultants are a team of experts and mentors collaborating with Rimal X across business, tech, marketing, and finance.', 'صفحة الدعم والاستشارات', 'Support & consulting page', 85),
  ((select id from cat), ARRAY['استشارات تقنية']::text[], ARRAY['technical consulting']::text[], 'هل توجد استشارات تقنية؟', 'Are there technical consultations?', 'نعم، تتوفر استشارات تقنية تغطي جوانب مثل بناء المنتج والبنية التقنية.', 'Yes, technical consultations are available covering areas like product build and tech architecture.', 'صفحة الدعم والاستشارات', 'Support & consulting page', 88),
  ((select id from cat), ARRAY['استشارات قانونية']::text[], ARRAY['legal consulting']::text[], 'هل توجد استشارات قانونية؟', 'Are there legal consultations?', 'نعم، تتوفر استشارات قانونية أساسية، وتُنسَّق الاستشارات المتخصصة أكثر حسب الحاجة.', 'Yes, basic legal consulting is available, with more specialized consultations coordinated as needed.', 'صفحة الدعم والاستشارات', 'Support & consulting page', 55),
  ((select id from cat), ARRAY['استشارات مالية']::text[], ARRAY['financial consulting']::text[], 'هل توجد استشارات مالية؟', 'Are there financial consultations?', 'نعم، تتوفر استشارات مالية تغطي التسعير، الميزانيات، والتخطيط المالي المبدئي للمشاريع.', 'Yes, financial consulting is available covering pricing, budgeting, and initial financial planning for projects.', 'صفحة الدعم والاستشارات', 'Support & consulting page', 82),
  ((select id from cat), ARRAY['استشارات تسويقية']::text[], ARRAY['marketing consulting']::text[], 'هل توجد استشارات تسويقية؟', 'Are there marketing consultations?', 'نعم، تتوفر استشارات تسويقية تساعد في بناء استراتيجية الوصول للعملاء والنمو.', 'Yes, marketing consulting is available to help build a customer acquisition and growth strategy.', 'صفحة الدعم والاستشارات', 'Support & consulting page', 85),
  ((select id from cat), ARRAY['استشارة أونلاين']::text[], ARRAY['online consultation']::text[], 'هل يمكن حجز استشارة أونلاين؟', 'Can I book a consultation online?', 'نعم، يمكن حجز وإجراء الجلسات الاستشارية عن بُعد عبر مكالمة فيديو حسب التنسيق مع الفريق.', 'Yes, consultation sessions can be booked and held remotely via video call, coordinated with the team.', 'صفحة الدعم والاستشارات', 'Support & consulting page', 82),
  ((select id from cat), ARRAY['مدة الجلسة']::text[], ARRAY['session duration']::text[], 'كم مدة الجلسة؟', 'How long is the session?', 'مدة الجلسة الاستشارية الدقيقة تختلف حسب نوعها، وتُحدَّد عند الحجز.', 'The exact consultation session duration varies by type and is set at the time of booking.', 'صفحة الدعم والاستشارات', 'Support & consulting page', 48),
  ((select id from cat), ARRAY['إعادة الحجز', 'استشارة']::text[], ARRAY['rebook', 'consultation']::text[], 'هل يمكن إعادة الحجز؟', 'Can I rebook?', 'نعم، يمكن إعادة حجز جلسة استشارية أخرى حسب التوفر والحاجة.', 'Yes, another consultation session can be rebooked based on availability and need.', 'صفحة الدعم والاستشارات', 'Support & consulting page', 80),
  ((select id from cat), ARRAY['استشارات للشركات']::text[], ARRAY['consulting for companies']::text[], 'هل يوجد استشارات للشركات؟', 'Are there consultations for companies?', 'نعم، تتوفر جلسات استشارية موجّهة خصيصًا لاحتياجات الشركات الناشئة والصغيرة.', 'Yes, consulting sessions tailored specifically to the needs of startups and small companies are available.', 'صفحة الدعم والاستشارات', 'Support & consulting page', 85),
  ((select id from cat), ARRAY['استشارات للأفراد']::text[], ARRAY['consulting for individuals']::text[], 'هل يوجد استشارات للأفراد؟', 'Are there consultations for individuals?', 'نعم، يمكن للأفراد أصحاب الأفكار حجز استشارات فردية لتطوير مشاريعهم.', 'Yes, individuals with an idea can book individual consultations to develop their projects.', 'صفحة الدعم والاستشارات', 'Support & consulting page', 85),
  ((select id from cat), ARRAY['براءات الاختراع']::text[], ARRAY['patents']::text[], 'هل تساعدون في براءات الاختراع؟', 'Do you help with patents?', 'دعم براءات الاختراع يكون عادة عبر توجيه أولي وربط بجهات متخصصة، وليس تقديم الخدمة القانونية الكاملة مباشرة.', 'Patent support is usually through initial guidance and referral to specialized parties, not a full in-house legal service.', 'صفحة الدعم والاستشارات', 'Support & consulting page', 48),
  ((select id from cat), ARRAY['بناء المنتج']::text[], ARRAY['build product']::text[], 'هل تساعدون في بناء المنتج؟', 'Do you help build the product?', 'نعم، يقدَّم دعم واستشارات في بناء المنتج (Product) ضمن برامج الحاضنة والمسرّعة والاستشارات المباشرة.', 'Yes, support and consulting for building the product are provided within the incubator, accelerator, and direct consulting.', 'صفحة الدعم والاستشارات', 'Support & consulting page', 85),
  ((select id from cat), ARRAY['دراسة الجدوى']::text[], ARRAY['feasibility study']::text[], 'هل تساعدون في دراسة الجدوى؟', 'Do you help with feasibility studies?', 'نعم، يساعد فريق رمال X رواد الأعمال في إعداد دراسة جدوى مبدئية لمشاريعهم.', 'Yes, the Rimal X team helps entrepreneurs prepare an initial feasibility study for their projects.', 'صفحة الدعم والاستشارات', 'Support & consulting page', 82);

-- تصنيف: الشراكات / Partnerships
with cat as (select id from categories where name_ar = 'الشراكات' limit 1)
insert into knowledge_base (category_id, keywords_ar, keywords_en, question_ar, question_en, answer_ar, answer_en, citation_ar, citation_en, confidence)
values
  ((select id from cat), ARRAY['أصبح شريكًا']::text[], ARRAY['become a partner']::text[], 'كيف أصبح شريكًا؟', 'How do I become a partner?', 'يمكن التقديم لتصبح شريكًا لرمال X عبر التواصل مع فريق الشراكات وشرح طبيعة الشراكة المقترحة.', 'You can apply to become a Rimal X partner by contacting the partnerships team and outlining the proposed partnership.', 'صفحة الشراكات', 'Partnerships page', 85),
  ((select id from cat), ARRAY['الجامعات', 'تعاون']::text[], ARRAY['universities', 'collaborate']::text[], 'هل يمكن للجامعات التعاون معكم؟', 'Can universities collaborate with you?', 'نعم، رمال X منفتحة على شراكات مع الجامعات لدعم ريادة الأعمال الطلابية والبحث التطبيقي.', 'Yes, Rimal X is open to partnerships with universities to support student entrepreneurship and applied research.', 'صفحة الشراكات', 'Partnerships page', 85),
  ((select id from cat), ARRAY['الشركات', 'تعاون']::text[], ARRAY['companies', 'collaborate']::text[], 'هل يمكن للشركات التعاون؟', 'Can companies collaborate?', 'نعم، يمكن للشركات التعاون مع رمال X عبر رعاية برامج، فعاليات مشتركة، أو دعم تقني/عيني.', 'Yes, companies can collaborate with Rimal X by sponsoring programs, co-hosting events, or providing technical/in-kind support.', 'صفحة الشراكات', 'Partnerships page', 85),
  ((select id from cat), ARRAY['رعايات']::text[], ARRAY['sponsorships']::text[], 'هل لديكم رعايات؟', 'Do you have sponsorships?', 'نعم، تتوفر فرص رعاية لفعاليات وبرامج رمال X للجهات الراغبة بالمشاركة.', 'Yes, sponsorship opportunities for Rimal X''s events and programs are available for interested parties.', 'صفحة الشراكات', 'Partnerships page', 82),
  ((select id from cat), ARRAY['مقترحات الشراكات']::text[], ARRAY['partnership proposals']::text[], 'هل تستقبلون مقترحات الشراكات؟', 'Do you accept partnership proposals?', 'نعم، يمكن إرسال مقترحات الشراكة عبر نموذج التواصل أو البريد الإلكتروني الخاص برمال X.', 'Yes, partnership proposals can be sent via the contact form or Rimal X''s email.', 'صفحة الشراكات', 'Partnerships page', 85),
  ((select id from cat), ARRAY['فعالية مشتركة']::text[], ARRAY['co-hosted event']::text[], 'هل يمكن إقامة فعالية مشتركة؟', 'Can we co-host an event?', 'نعم، يمكن التنسيق لإقامة فعاليات مشتركة مع رمال X حسب الموضوع والجمهور المستهدف.', 'Yes, co-hosted events with Rimal X can be arranged depending on the topic and target audience.', 'صفحة الشراكات', 'Partnerships page', 82),
  ((select id from cat), ARRAY['مزايا للشركاء']::text[], ARRAY['partner benefits']::text[], 'هل توجد مزايا للشركاء؟', 'Are there benefits for partners?', 'نعم، يحصل الشركاء عادة على ظهور إعلامي، وصول لمجتمع رواد الأعمال، وفرص تعاون مباشرة.', 'Yes, partners typically receive media visibility, access to the entrepreneur community, and direct collaboration opportunities.', 'صفحة الشراكات', 'Partnerships page', 78),
  ((select id from cat), ARRAY['فريق الشراكات']::text[], ARRAY['partnerships team']::text[], 'كيف أتواصل مع فريق الشراكات؟', 'How do I contact the partnerships team?', 'يمكن التواصل مع فريق الشراكات عبر نموذج التواصل في الموقع مع تحديد أن الطلب يخص شراكة.', 'You can contact the partnerships team via the website''s contact form, specifying that the request is partnership-related.', 'صفحة الشراكات', 'Partnerships page', 82),
  ((select id from cat), ARRAY['مذكرة تفاهم']::text[], ARRAY['mou', 'memorandum']::text[], 'هل يمكن توقيع مذكرة تفاهم؟', 'Can we sign an MOU?', 'نعم، يمكن توقيع مذكرة تفاهم رسمية بين رمال X والجهة الشريكة بعد الاتفاق على نطاق التعاون.', 'Yes, a formal MOU can be signed between Rimal X and the partner entity after agreeing on the scope of collaboration.', 'صفحة الشراكات', 'Partnerships page', 82),
  ((select id from cat), ARRAY['نموذج الشراكات']::text[], ARRAY['partnership form']::text[], 'هل يوجد نموذج خاص بالشراكات؟', 'Is there a specific partnership form?', 'نعم، يتوفر نموذج تواصل يمكن استخدامه لتقديم طلبات ومقترحات الشراكة.', 'Yes, a contact form is available for submitting partnership requests and proposals.', 'صفحة الشراكات', 'Partnerships page', 80);

-- تصنيف: التواصل والطلبات / Contact & Requests
with cat as (select id from categories where name_ar = 'التواصل والطلبات' limit 1)
insert into knowledge_base (category_id, keywords_ar, keywords_en, question_ar, question_en, answer_ar, answer_en, citation_ar, citation_en, confidence)
values
  ((select id from cat), ARRAY['كيف أتواصل', 'طلبات']::text[], ARRAY['how contact', 'requests']::text[], 'كيف أتواصل معكم؟', 'How can I contact you?', 'يمكن التواصل مع رمال X عبر البريد الإلكتروني أو نموذج التواصل في الموقع.', 'You can contact Rimal X via email or the contact form on the website.', 'صفحة التواصل والطلبات', 'Contact & requests page', 90),
  ((select id from cat), ARRAY['إرسال استفسار']::text[], ARRAY['send inquiry']::text[], 'كيف أرسل استفسارًا؟', 'How do I send an inquiry?', 'يمكن إرسال أي استفسار عبر نموذج التواصل في الموقع أو البريد الإلكتروني وسيتم الرد عليه من الفريق.', 'Any inquiry can be sent via the website''s contact form or email, and the team will respond.', 'صفحة التواصل والطلبات', 'Contact & requests page', 88),
  ((select id from cat), ARRAY['طلب زيارة']::text[], ARRAY['request visit']::text[], 'كيف أطلب زيارة؟', 'How do I request a visit?', 'يمكن طلب زيارة لمقر رمال X عبر التواصل المباشر مع الفريق لتنسيق الموعد المناسب.', 'A visit to the Rimal X office can be requested by contacting the team directly to coordinate a suitable time.', 'صفحة التواصل والطلبات', 'Contact & requests page', 85),
  ((select id from cat), ARRAY['إبلاغ عن مشكلة']::text[], ARRAY['report a problem']::text[], 'كيف أبلغ عن مشكلة؟', 'How do I report a problem?', 'يمكن الإبلاغ عن أي مشكلة عبر نموذج التواصل في الموقع أو البريد الإلكتروني مع وصف واضح للمشكلة.', 'Any problem can be reported via the website''s contact form or email, with a clear description of the issue.', 'صفحة التواصل والطلبات', 'Contact & requests page', 85),
  ((select id from cat), ARRAY['تقديم اقتراح']::text[], ARRAY['submit suggestion']::text[], 'كيف أقدم اقتراحًا؟', 'How do I submit a suggestion?', 'يمكن تقديم أي اقتراح لتطوير خدمات رمال X عبر نموذج التواصل في الموقع.', 'Any suggestion to improve Rimal X''s services can be submitted via the website''s contact form.', 'صفحة التواصل والطلبات', 'Contact & requests page', 85),
  ((select id from cat), ARRAY['تقديم شكوى']::text[], ARRAY['file a complaint']::text[], 'كيف أقدم شكوى؟', 'How do I file a complaint?', 'يمكن تقديم الشكاوى عبر نموذج التواصل أو البريد الإلكتروني، وسيتم التعامل معها من قبل الفريق المختص.', 'Complaints can be submitted via the contact form or email, and will be handled by the relevant team.', 'صفحة التواصل والطلبات', 'Contact & requests page', 85),
  ((select id from cat), ARRAY['يستغرق الرد']::text[], ARRAY['response time']::text[], 'كم يستغرق الرد؟', 'How long does a response take?', 'زمن الرد الدقيق قد يختلف حسب نوع الطلب وضغط العمل، ويُبذل الجهد للرد في أقرب وقت ممكن.', 'The exact response time may vary depending on the request type and workload, with best effort made to respond as soon as possible.', 'صفحة التواصل والطلبات', 'Contact & requests page', 50),
  ((select id from cat), ARRAY['التواصل عبر البريد']::text[], ARRAY['contact by email']::text[], 'هل يمكن التواصل عبر البريد الإلكتروني؟', 'Can I contact you by email?', 'نعم، يمكن التواصل مع رمال X عبر البريد الإلكتروني المتاح في صفحة التواصل بالموقع.', 'Yes, you can contact Rimal X via the email address available on the website''s contact page.', 'صفحة التواصل والطلبات', 'Contact & requests page', 90),
  ((select id from cat), ARRAY['التواصل عبر الهاتف']::text[], ARRAY['contact by phone']::text[], 'هل يمكن التواصل عبر الهاتف؟', 'Can I contact you by phone?', 'توفر رقم هاتف مباشر للتواصل يحتاج تأكيدًا من الفريق؛ الأضمن حاليًا التواصل عبر البريد الإلكتروني أو نموذج الموقع.', 'Availability of a direct phone number needs confirmation from the team; email or the website''s contact form is currently the most reliable option.', 'صفحة التواصل والطلبات', 'Contact & requests page', 45),
  ((select id from cat), ARRAY['آخر الأخبار']::text[], ARRAY['latest news']::text[], 'كيف أعرف آخر الأخبار والإعلانات؟', 'How do I stay updated on news and announcements?', 'يمكن متابعة آخر أخبار وإعلانات رمال X عبر الموقع الإلكتروني وحساباتها على وسائل التواصل الاجتماعي.', 'You can follow Rimal X''s latest news and announcements via the website and its social media accounts.', 'صفحة التواصل والطلبات', 'Contact & requests page', 88);

-- =========================================================
-- 3) أسئلة وخيارات تدفق التأهيل (نفس قيم MockChatAdapter.ts الحالية بالضبط)
-- =========================================================

insert into qualification_questions (id, question_ar, question_en, sort_order) values
  ('budget', 'ما هي ميزانيتك الشهرية التقريبية؟', 'What''s your approximate monthly budget?', 1),
  ('teamSize', 'كم عدد أفراد فريقك؟', 'How many people are on your team?', 2),
  ('usageType', 'ما هو نوع الاستخدام الأساسي؟', 'What''s the main type of use?', 3);

insert into qualification_options (id, question_id, label_ar, label_en, sort_order) values
  ('b1', 'budget', 'أقل من 1,000 ريال', 'Under SAR 1,000', 1),
  ('b2', 'budget', '1,000 - 3,000 ريال', 'SAR 1,000 - 3,000', 2),
  ('b3', 'budget', 'أكثر من 3,000 ريال', 'Over SAR 3,000', 3),
  ('t1', 'teamSize', 'فردي (شخص واحد)', 'Just me', 1),
  ('t2', 'teamSize', 'فريق صغير (2-5)', 'Small team (2-5)', 2),
  ('t3', 'teamSize', 'فريق أكبر (6+)', 'Larger team (6+)', 3),
  ('u1', 'usageType', 'عمل يومي مكتبي', 'Daily desk work', 1),
  ('u2', 'usageType', 'اجتماعات فقط', 'Meetings only', 2),
  ('u3', 'usageType', 'تدريب وفعاليات', 'Training & events', 3);

-- =========================================================
-- 4) قواعد الترشيح (تُطابق منطق getRecommendation الحالي بالضبط)
-- =========================================================

insert into recommendation_rules (match_conditions, priority, result_id, name_ar, name_en, reason_template_ar, reason_template_en) values
  ('{"usageType":"u2"}'::jsonb, 30, 'meeting-room', 'باقة قاعات الاجتماعات', 'Meeting Room Package', 'بناءً على ميزانيتك ({{budgetLabel}}) وعدد فريقك ({{teamLabel}})، هذا الخيار الأنسب لاستخدامك ({{usageLabel}}).', 'Based on your budget ({{budgetLabel}}) and team size ({{teamLabel}}), this fits your usage ({{usageLabel}}) best.'),
  ('{"usageType":"u3"}'::jsonb, 30, 'training-hall', 'قاعة التدريب والفعاليات', 'Training & Events Hall', 'بناءً على ميزانيتك ({{budgetLabel}}) وعدد فريقك ({{teamLabel}})، هذا الخيار الأنسب لاستخدامك ({{usageLabel}}).', 'Based on your budget ({{budgetLabel}}) and team size ({{teamLabel}}), this fits your usage ({{usageLabel}}) best.'),
  ('{"teamSize":"t1","budget":"b1"}'::jsonb, 20, 'hot-desk', 'مقعد مرن (Hot Desk)', 'Hot Desk', 'بناءً على ميزانيتك ({{budgetLabel}}) وعدد فريقك ({{teamLabel}})، هذا الخيار الأنسب لاستخدامك ({{usageLabel}}).', 'Based on your budget ({{budgetLabel}}) and team size ({{teamLabel}}), this fits your usage ({{usageLabel}}) best.'),
  ('{"teamSize":"t1"}'::jsonb, 10, 'dedicated-desk', 'مكتب مخصص (Dedicated Desk)', 'Dedicated Desk', 'بناءً على ميزانيتك ({{budgetLabel}}) وعدد فريقك ({{teamLabel}})، هذا الخيار الأنسب لاستخدامك ({{usageLabel}}).', 'Based on your budget ({{budgetLabel}}) and team size ({{teamLabel}}), this fits your usage ({{usageLabel}}) best.'),
  ('{"budget":"b3"}'::jsonb, 5, 'private-office', 'مكتب خاص (Private Office)', 'Private Office', 'بناءً على ميزانيتك ({{budgetLabel}}) وعدد فريقك ({{teamLabel}})، هذا الخيار الأنسب لاستخدامك ({{usageLabel}}).', 'Based on your budget ({{budgetLabel}}) and team size ({{teamLabel}}), this fits your usage ({{usageLabel}}) best.'),
  ('{}'::jsonb, 0, 'dedicated-desk-team', 'مكاتب مخصصة للفريق (Dedicated Desks)', 'Team Dedicated Desks', 'بناءً على ميزانيتك ({{budgetLabel}}) وعدد فريقك ({{teamLabel}})، هذا الخيار الأنسب لاستخدامك ({{usageLabel}}).', 'Based on your budget ({{budgetLabel}}) and team size ({{teamLabel}}), this fits your usage ({{usageLabel}}) best.');
